name: Clean GitHub Container Registry

on:
  workflow_dispatch:

jobs:
  clean-ghcr:

    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: GitHub container registry cleaning
        uses: pcasteran/ghcr-cleaning-action@v1.4.0
        with:
          user: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          package: caddy-with-namedotcom
          repository: mpgirro/caddy-with-namedotcom
